### ISSUE TITLE
Error: PlatformException(error, Expected a value of type 'int', but got one of type 'String', null, null)

### ISSUE THREAD

**Issue by Matrinica** [Kent1011/client_information#1]
Got an exception on web. Launched with Chrome.

```
Error: PlatformException(error, Expected a value of type 'int', but got one of type 'String', null, null)
    at Object.throw_ [as throw] (http://localhost:61847/dart_sdk.js:5334:11)
    at StandardMethodCodec.decodeEnvelope (http://localhost:61847/packages/flutter/src/services/system_channels.dart.lib.js:792:19)
    at MethodChannel._invokeMethod (http://localhost:61847/packages/flutter/src/services/system_channels.dart.lib.js:956:47)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:61847/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:61847/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:61847/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:61847/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:61847/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:61847/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:61847/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:61847/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:61847/dart_sdk.js:39182:13)
    at http://localhost:61847/dart_sdk.js:34689:9
```

**Comment by Bes79** [comment]
Same issue

**Comment by Kent1011** [comment]
The last version 2.0.1 fixed.

**Comment by tauu** [comment]
Is it possible that the bug is still present in 2.0.1 ? Looking at the last commit, the changelog and version number have been update, but the actual fix seems to be missing.
